### ISSUE TITLE
TODO Week 1

### ISSUE THREAD

**Issue by samrass** [samrass/projinda18#1]
[Vecka 1](https://kth.instructure.com/courses/5205/assignments/24691)

- [x] Write a short Project Description, using the repo's README

- [x] Decide and map out the Project Plan using Features/Milestones via Issue Tracker
- [x] Decide on a topic

- [x] Present topic at övning

- [x] Start developing
- [x] Create a single repo on KTH Github and share with partner

- [x] Find a partner

**Comment by pj-hugo** [comment]
Completed.
